name: Headlamp plugin linting, type checking, and testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HEADLAMP_PLUGIN_VERSION: latest

jobs:
  # Get list of folders containing headlamp plugins
  # We need a separate step to be able to pass the list to the matrix of the build job
  find_plugin_dirs:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v2
      - id: dirs
        run: echo "dirs=$(grep -m1 -lR @kinvolk/headlamp-plugin ./*/package.json | xargs -n1 dirname | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}

  build:
    needs: find_plugin_dirs
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ matrix.dir }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        dir: ${{ fromJson(needs.find_plugin_dirs.outputs.dirs) }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ matrix.dir }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build ${{ matrix.dir }}
        run: npm run build

      - name: Typecheck ${{ matrix.dir }}
        run: npm run tsc

      - name: Lint ${{ matrix.dir }}
        run: npm run lint

      - name: Check formatting ${{ matrix.dir }}
        run: npm run format -- --check

      - name: Test ${{ matrix.dir }}
        run: npm run test
